grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6
      - 8
      - 4
  module_2:
    class: SVR
    module: sklearn.svm
    params:
      kernel: linear
      gamma: scale
    search_param_grid:
      kernel:
      - linear
      - poly
      gamma:
      - scale
      - auto
